### ISSUE TITLE
static library error for dcm2niix build

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/pnlpipe_software#1]
Suggestion by @sbouix to solve static library error:

https://github.com/pnlbwh/pnlpipe_software/blob/master/dcm2niix.py#L32

```
cmake(repo, "-DUSE_STATIC_RUNTIME=OFF")
```
or `yum install libsdtc++-static`

**Comment by tashrifbillah** [comment]
Updating submodule urges updating `pnlpipe` and `pnlNipype` with updated hashes of the submodule.

**Comment by tashrifbillah** [comment]
> cmake(repo, "-DUSE_STATIC_RUNTIME:BOOL=OFF")

**Comment by tashrifbillah** [comment]
Hi @neurolabusc,

Would you consider `USE_STATIC_RUNTIME=OFF` [here](https://github.com/rordenlab/dcm2niix/search?q=USE_STATIC_RUNTIME&unscoped_q=USE_STATIC_RUNTIME)? I built dcm2niix in about six machines in and out of the country where they didn't have `libsdtc++-static` library by default. So I either had to install the library or turn it OFF through `ccmake`.

I understand this library might be necessary to optimize performance of `dcm2niix` in which case it is best not to. Just let me know.

**Comment by neurolabusc** [comment]
@ningfei, as you developed the super build script, do you have any thoughts on this? I do worry about unintended consequences for other users, and we use these build scripts to automatically create and test each commit.

@tashrifbillah am I correct that when the install fails it emits the error
```
USE_STATIC_RUNTIME set to ON but "libstdcxx.a" not found! "yum install libstdc++-static" to resolve the error.
```
and one the systems you tested either of these two options resolves the problem?

**Comment by ningfei** [comment]
We set `USE_STATIC_RUNTIME` set to `ON` to make the artifacts generated by Travis or Appvoyer compatible with most of the systems. So the users won't have problems in case that their system `libstdc++` is too old or on windows they don't have the correct runtime installed. This is purely for the ease of distribution. In case of pnlpipe or similar tool which actually builds `dcm2niix` locally, it is also safe to turn it `OFF` by using the cmake option `-DUSE_STATIC_RUNTIME:BOOL=OFF`. I think the current way here https://github.com/pnlbwh/pnlpipe_software/blob/master/dcm2niix.py#L32 is a good solution.

**Comment by tashrifbillah** [comment]
@neurolabusc , yes are are correct.

> In case of pnlpipe or similar tool which actually builds dcm2niix locally, it is also safe to turn it OFF by using the cmake option -DUSE_STATIC_RUNTIME:BOOL=OFF.

@ningfei , the concern here is- a user might not have knowledge of `ccmake` which they should use to turn OFF the option, nor may have sudo access to actually `yum install` something. So, when they experience the error, it raises a red flag towards moving forward with `dcm2niix`. My suggestion was to make `dcm2niix` installation a hassle-less process for clinical researchers with potentially less Linux knowledge.

**Comment by ningfei** [comment]
Understood. But users trying to build `dcm2niix` locally themselves should already have `ccmake` and see the option `USE_STATIC_RUNTIME` in the menu during configuration. And they also have tools like `pnlpipe` to make to the build/installation hassle-less :)  If we change this default setting from `dcm2niix` side, it might break other tools like `conda forge` or `brew` which already integrate `dcm2niix` in their repository. Maybe we should show the following error message instead:
`USE_STATIC_RUNTIME set to ON but "libstdcxx.a" not found! Set it to OFF or "yum install libstdc++-static" to resolve the error`.
Or even fallback to dynamic runtime when `libstdcxx.a` is not found
